/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object accept(jmmVisitor visitor, SymbolTable data)  throws SemanticException{

    SymbolTable classSymbolTable = new SymbolTable(this, data);


    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.accept(visitor, classSymbolTable);
        }
      }
    }

    return
    visitor.visit(this, classSymbolTable);
  }
}
/* JavaCC - OriginalChecksum=b31e1758e882a104881e49b709ce83b8 (do not edit this line) */
