import java.util.*;

/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodDeclaration extends SimpleNode {
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object accept(jmmVisitor visitor, SymbolTable data) throws SemanticException {

    SymbolTable methodSymbolTable = new SymbolTable(this, data);

    List<List<String>> argTypes = new ArrayList<>();
    List<String> arg = new ArrayList<>();
    if(jmmTreeConstants.jjtNodeName[((SimpleNode) this.jjtGetChild(2)).getId()].equals("Arguments")){
      for(int i=0; i<((SimpleNode) this.jjtGetChild(2)).jjtGetNumChildren(); i+=2){
        arg.add(((SimpleNode)this.jjtGetChild(2).jjtGetChild(i)).jjtGetValue().toString());
        arg.add(((SimpleNode)this.jjtGetChild(2).jjtGetChild(i+1)).jjtGetValue().toString());
        argTypes.add(arg);
        arg = new ArrayList<>();
      }
    }
    else{
      arg.add("void");
      arg.add("null");
      argTypes.add(arg);
    }

    for(int i=0; i<argTypes.size(); i++){
      String arg_id = argTypes.get(i).get(1);
      String arg_type = argTypes.get(i).get(0);
      STVarDeclaration varEntry = new STVarDeclaration(arg_id, arg_type, "", line, column);
      varEntry.setInitialized(true);
      methodSymbolTable.insert(arg_id, varEntry);
    }

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.accept(visitor, methodSymbolTable);
        }
      }
    }
    return
    visitor.visit(this, methodSymbolTable);
  }
}
/* JavaCC - OriginalChecksum=75255b2bb84861a868b67cc78a24444a (do not edit this line) */
