/* Generated By:JJTree: Do not edit this line. ASTStart_parser.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStart_parser extends SimpleNode {
  public ASTStart_parser(int id) {
    super(id);
  }

  public ASTStart_parser(jmm p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object accept(jmmVisitor visitor, SymbolTable data) throws SemanticException{

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.accept(visitor, data);
        }
      }
    }


    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b4e71ea458f2e62d07bd8cff9cb5c37e (do not edit this line) */
