/* Generated By:JavaCC: Do not edit this line. jmmVisitor.java Version 6.1_2 */
public interface jmmVisitor
{
  public Object visit(ASTStart_parser node, SymbolTable data) throws SemanticException;
  public Object visit(ASTDot node, SymbolTable data) throws SemanticException;
  public Object visit(ASTReturn node, SymbolTable data) throws SemanticException;
  public Object visit(ASTImport node, SymbolTable data) throws SemanticException;
  public Object visit(ASTArguments node, SymbolTable data) throws SemanticException;
  public Object visit(ASTClassDeclaration node, SymbolTable data) throws SemanticException;
  public Object visit(ASTExtends node, SymbolTable data) throws SemanticException;
  public Object visit(ASTVarDeclaration node, SymbolTable data) throws SemanticException;
  public Object visit(ASTMainDeclaration node, SymbolTable data) throws SemanticException;
  public Object visit(ASTMethodDeclaration node, SymbolTable data) throws SemanticException;
  public Object visit(ASTType node, SymbolTable data) throws SemanticException;
  public Object visit(ASTStatement node, SymbolTable data) throws SemanticException;
  public Object visit(ASTIf node, SymbolTable data) throws SemanticException;
  public Object visit(ASTCondition node, SymbolTable data) throws SemanticException;
  public Object visit(ASTWhile node, SymbolTable data) throws SemanticException;
  public Object visit(ASTExpression node, SymbolTable data) throws SemanticException;
  public Object visit(ASTEquals node, SymbolTable data) throws SemanticException;
  public Object visit(ASTLeftEqual node, SymbolTable data) throws SemanticException;
  public Object visit(ASTRightEqual node, SymbolTable data) throws SemanticException;
  public Object visit(ASTOperator node, SymbolTable data) throws SemanticException;
  public Object visit(ASTNot node, SymbolTable data) throws SemanticException;
  public Object visit(ASTIntegerLiteral node, SymbolTable data) throws SemanticException;
  public Object visit(ASTTrue node, SymbolTable data) throws SemanticException;
  public Object visit(ASTFalse node, SymbolTable data) throws SemanticException;
  public Object visit(ASTThis node, SymbolTable data) throws SemanticException;
  public Object visit(ASTNew node, SymbolTable data) throws SemanticException;
  public Object visit(ASTLength node, SymbolTable data) throws SemanticException;
  public Object visit(ASTIdentifier node, SymbolTable data) throws SemanticException;
  public Object visit(ASTVoid node, SymbolTable data) throws SemanticException;
  public Object visit(ASTArrayAccess node, SymbolTable data) throws SemanticException;
  //public Object visit(SimpleNode node, SymbolTable data);
}
/* JavaCC - OriginalChecksum=bbfd0e8ef3519d0661282d13f1420f2b (do not edit this line) */
