//import javax.xml.soap.Node;

//import javax.xml.soap.Node;

/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node, ASTNode {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected jmm parser;
  protected boolean isStatic = false;
  protected int line, column;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(jmm p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return jmmTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    //System.out.println(toString(prefix));

    switch (this.id){
      case jmmTreeConstants.JJTOPERATOR:
      case jmmTreeConstants.JJTIDENTIFIER:
      case jmmTreeConstants.JJTTYPE:
      case jmmTreeConstants.JJTINTEGERLITERAL:
        System.out.println(toString(prefix) + " [ " + this.value + " ]");break;
      default:
        System.out.println(toString(prefix));break;
    }

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + "\t");
        }
      }
    }
  }
  
  public int getId() {
    return id;
  }

  public boolean isStatic() {
    return isStatic;
  }

  public int getLine() {
    return line;
  }
  
  public int getColumn() {
    return column;
  }

  @Override
  public Object accept(jmmVisitor visitor, SymbolTable data) throws SemanticException{

    if(children != null){
      System.out.println("LENGTH: " + children.length);
        for(int i = 0; i < children.length; i++){
          SimpleNode node = (SimpleNode) children[i];
          if(node != null){
            System.out.println(node);
            node.accept(visitor, data);
          }
        }
    }
    
    
    return data;
  }
  
}

/* JavaCC - OriginalChecksum=0e394400cba5984c74c17a30bf5995e7 (do not edit this line) */
